name: 🚀 CI - Continuous Development

on:
  push:
    branches: ['main']

env:
  DOCKER_IMAGE: ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_PROJECT }}/${{ github.event.repository.name }}:${{ github.ref_name }}_${{ github.sha }}
  DOCKER_CONTAINER: ${{ github.event.repository.name }}
  DOCKER_PLATFORM: linux/amd64
  APP_INTERNAL_PORT: ${{ secrets.APP_INTERNAL_PORT || '80' }}
  APP_EXTERNAL_PORT: ${{ secrets.APP_EXTERNAL_PORT_DEV || secrets.APP_PORT || '3000' }}
  DEPLOY_HOST: ${{ secrets.HOST_PRODUCTION }}
  DEPLOY_USERNAME: ${{ secrets.USERNAME_PRODUCTION }}
  DEPLOY_KEY: ${{ secrets.KEY_PRODUCTION }}
  DEPLOY_PORT: ${{ secrets.PORT_PRODUCTION }}
  ENV_CONFIG: ${{ secrets.ENV_PRODUCTION }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set build time
        run: echo "BUILD_TIME=$(date '+%Y-%m-%d %H:%M:%S')" >> "$GITHUB_ENV"

      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📋 Build information
        run: |
          echo "🚀 Starting React App Build"
          echo "👤 Author: ${{ github.actor }}"
          echo "🏷️ Branch: ${{ github.ref_name }}"

      - name: 📄 Create environment file
        run: |
          echo "📄 Creating environment configuration for React..."
          echo "${{ env.ENV_CONFIG }}" > .env

      - name: 🔐 Registry login
        run: |
          echo "🔐 Authenticating with Docker registry..."
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: 🏗️ Build docker image
        run: |
          echo "🏗️ Building Docker image for React app..."
          docker build --platform ${{ env.DOCKER_PLATFORM }} -t ${{ env.DOCKER_IMAGE }} .
        
      - name: 📤 Push to registry
        run: |
          echo "📤 Pushing React app image to registry..."
          docker push ${{ env.DOCKER_IMAGE }}

      - name: 🎯 Build summary
        run: |
          echo "🎉 REACT BUILD COMPLETED"
          echo "⏰ Time: ${{ env.BUILD_TIME }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set deploy time
        run: echo "DEPLOY_TIME=$(date '+%Y-%m-%d %H:%M:%S')" >> "$GITHUB_ENV"

      - name: 🚀 Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USERNAME }}
          key: ${{ env.DEPLOY_KEY }}
          port: ${{ env.DEPLOY_PORT }}
          script: |
            echo "🚀 Starting deployment for React app..."
            echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
            docker pull ${{ env.DOCKER_IMAGE }}
            docker rm -f ${{ env.DOCKER_CONTAINER }} || true
            docker run --name ${{ env.DOCKER_CONTAINER }} --restart always -dp ${{ env.APP_EXTERNAL_PORT }}:${{ env.APP_INTERNAL_PORT }} ${{ env.DOCKER_IMAGE }}
            echo "✅ React App Deployment completed"

      - name: 🎉 Deploy summary
        run: |
          echo "🎉 REACT APP DEPLOYMENT COMPLETED"
          echo "👤 Deployed by: ${{ github.actor }}"
          echo "⏰ Time: ${{ env.DEPLOY_TIME }}"